name: auto-format

on:
  push:
    branches: master

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: PNPM install
        run: pnpm install --ignore-scripts

      - name: Format
        run: pnpm format

      - name: Check if format produces git diff
        id: ifChange
        run: git diff --exit-code || echo "::set-output name=changed::yes"

      - name: Create PR
        if: steps.ifChange.outputs.changed == 'yes'
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.TEDIUM_BOT_GITHUB_ACCESS_TOKEN }}
          commit-message: Auto-format
          committer: Polymer GitHub Actions Robot <format-bot@polymer-project.org>
          title: Auto-format master branch
          body: This PR was auto generated by the auto-format GitHub action.
          reviewers: azakus,asyncliz
          branch: auto-format-action
          branch-suffix: short-commit-hash
          labels: "Ready for Google"
