name: Build and Deploy Demos
on:
  push:
    branches: master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'pnpm'
      - name: Install and Build
        run: |
          pnpm install
          pnpm build
          pnpm build:demos

      - name: Deploy Demos
        uses: JamesIves/github-pages-deploy-action@3.4.9
        with:
          ACCESS_TOKEN: ${{ secrets.TEDIUM_BOT_GITHUB_ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
