name: Publish & Release
on:
  workflow_dispatch:
    inputs:
      next_version:
        description: "Changelog Next version tag"
        required: false
      commit_message:
        description: "Commit message"
        required: false
      version_type:
        type: choice
        description: "Version type"
        required: false
        options:
          - patch
          - minor
          - major
          - rc
      release_channel:
        type: choice
        description: "Release channel"
        required: false
        options:
          - next
          - latest
          - beta
          - alpha

jobs:
  changelog:
    uses: ./.github/workflows/changelog.yml
    with:
      next_version: ${{ github.event.inputs.next_version }}
      commit_message: ${{ github.event.inputs.commit_message }}
  release_publish:
    needs: changelog
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Pull changes
        run: git pull
      - name: Automated Version Bump
        id: version_bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: ${{ github.event.inputs.version_type }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          tag_name: ${{ steps.version_bump.outputs.newTag }}
      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish
        run: pnpm publish --access public --tag ${{ github.event.inputs.release_channel }}
