name: MWC Release (Canary)

# This workflow creates a pre-release and publishes packages to NPM with canary
# tag on every commit to master.

on:
  push:
    branches:
      - master
    paths:
      - 'packages/**/*.ts'
      - 'packages/**/*.scss'
      - '**/package*.json'
      - '**/.npmignore'
      - '**/tsconfig.json'

jobs:
  release-canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout master branch
        # GITHUB_REF:11 gets `refs/heads/master` => `master`.
        # See https://github.com/actions/checkout/issues/6
        run: |
          git checkout "${GITHUB_REF:11}"
          git pull
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'pnpm'
      - name: PNPM install
        run: pnpm install --ignore-scripts
      - name: Create canary release
        run: |
          lerna version preminor --no-git-tag-version --no-push --preid canary.$(git rev-parse --short HEAD) --yes --exact
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "chore: Publish"
      - name: Publish to NPM registry with canary tag
        run: pnpm -r publish --tag canary
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
