name: tests

on: [ push, pull_request ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'pnpm'
      - name: PNPM install
        run: pnpm install --ignore-scripts

      - name: Lerna bootstrap
        run: pnpm bootstrap

      - name: Check format
        run: pnpm format:check

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'pnpm'
      - name: PNPM install
        run: pnpm install --ignore-scripts

      - name: Lerna bootstrap
        run: pnpm bootstrap

      - name: Build component Sass
        run: pnpm build:styling

      - name: Compile component TypeScript
        run: pnpm build:typescript

      - name: Compile test TypeScript
        run: pnpm build:tests

      - name: Unit tests
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: |
          # Don't run Sauce from a forked repo, since the code may not be trusted
          # and therefore secrets like the Sauce password are not available.
          # GITHUB_HEAD_REF is only defined when building a fork.
          if [ ! "$GITHUB_HEAD_REF" ]; then
            export USE_SAUCE=true
            export SAUCE_BUILD_ID=mwc-tests-${GITHUB_EVENT_NAME}-${GITHUB_ACTION}-${GITHUB_SHA}
            export SAUCE_TUNNEL_ID=${SAUCE_BUILD_ID}-tunnel
          fi
          pnpm test
